CREATE DATABASE form;

USE form;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NULL,
    apellido VARCHAR(255) NULL,
    codigo INT NULL,
    id_revisor INT NULL,
    FOREIGN KEY (id_revisor) REFERENCES revisores(id) ON DELETE SET NULL ON UPDATE CASCADE
);